/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.pau.hsqldbproject;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author said
 */
public class NewJFrame2 extends javax.swing.JFrame {

    DBHandler dbh = null;//DBHandler class to help database operations
    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_department = new javax.swing.JTextField();
        text_title = new javax.swing.JTextField();
        text_lastname = new javax.swing.JTextField();
        text_email = new javax.swing.JTextField();
        text_firstname = new javax.swing.JTextField();
        label_title = new javax.swing.JLabel();
        label_lastname = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_department = new javax.swing.JLabel();
        label_firstname = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buton_ekle = new javax.swing.JButton();
        label_firstname1 = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("kisi ekle");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        label_title.setText("Title");

        label_lastname.setText("Last Name");

        label_email.setText("Email");

        label_department.setText("Department");

        label_firstname.setText("First Name");

        jButton1.setText("iptal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buton_ekle.setText("ekle");
        buton_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_ekleActionPerformed(evt);
            }
        });

        label_firstname1.setText("ID");

        text_id.setDoubleBuffered(true);
        text_id.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buton_ekle)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_title)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_firstname)
                            .addComponent(label_lastname)
                            .addComponent(label_email)
                            .addComponent(label_department)
                            .addComponent(label_firstname1))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_id)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text_firstname)
                                .addComponent(text_lastname)
                                .addComponent(text_email)
                                .addComponent(text_department)
                                .addComponent(text_title, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_firstname1)
                    .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_firstname)
                    .addComponent(text_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_lastname)
                    .addComponent(text_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_email)
                    .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_department)
                    .addComponent(text_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_title)
                    .addComponent(text_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buton_ekle))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosed

    private void buton_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_ekleActionPerformed
        // TODO add your handling code here
        NewJFrame mainframe=new NewJFrame();
        if(buton_ekle.getText().equalsIgnoreCase("ekle")){
        String sql = "INSERT INTO Employee (FIRSTNAME, LASTNAME, EMAIL, DEPARTMENT, TITLE)\nVALUES('"+text_firstname.getText()+"','"+text_lastname.getText()+"','"+text_email.getText()+"','"+text_department.getText()+"','"+text_title.getText()+"')";
        String connectionString = "jdbc:hsqldb:file:db/employeedb";
        try {
            dbh = new DBHandler(connectionString);
            dbh.executeNonQuery(sql);
            JOptionPane.showMessageDialog(this, "Ekleme yapıldı...");    
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Bu mail adresi başkası tarafından kullanılmaktadır..");
        }
       
        }
        else{
            String sql = "UPDATE Employee SET FIRSTNAME='"+text_firstname.getText()+"', LASTNAME='"+text_lastname.getText()+"', EMAIL='"+text_email.getText()+"', DEPARTMENT='"+text_department.getText()+"', TITLE='"+text_title.getText()+"' WHERE ID="+text_id.getText();
            String connectionString = "jdbc:hsqldb:file:db/employeedb";
            try {
            dbh = new DBHandler(connectionString);
            dbh.executeNonQuery(sql);
            JOptionPane.showMessageDialog(this, "Guncelleme yapıldı...");
            this.dispose();
           } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bu mail adresi başkası tarafından kullanılmaktadır..");
        }
        
        }
       
    }//GEN-LAST:event_buton_ekleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buton_ekle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel label_department;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_firstname;
    public javax.swing.JLabel label_firstname1;
    private javax.swing.JLabel label_lastname;
    private javax.swing.JLabel label_title;
    public javax.swing.JTextField text_department;
    public javax.swing.JTextField text_email;
    public javax.swing.JTextField text_firstname;
    public javax.swing.JTextField text_id;
    public javax.swing.JTextField text_lastname;
    public javax.swing.JTextField text_title;
    // End of variables declaration//GEN-END:variables
}
