/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.pau.hsqldbproject;

import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author said
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
     DBHandler dbh = null;//DBHandler class to help database operations
     static Connection connection = null;//Pure Connection class
     String connectionString = "jdbc:hsqldb:file:db/employeedb";
     int rowCount;
    private ActionEvent evt;
    public NewJFrame() {
        initComponents();
        buton_browseActionPerformed(evt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buton_previous = new javax.swing.JButton();
        buton_next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        text_currentPage = new javax.swing.JTextField();
        text_page = new javax.swing.JTextField();
        label_email = new javax.swing.JLabel();
        label_firstname = new javax.swing.JLabel();
        label_department = new javax.swing.JLabel();
        label_employee = new javax.swing.JLabel();
        label_title = new javax.swing.JLabel();
        label_lastname = new javax.swing.JLabel();
        text_employee = new javax.swing.JTextField();
        text_firstname = new javax.swing.JTextField();
        text_lastname = new javax.swing.JTextField();
        text_email = new javax.swing.JTextField();
        text_department = new javax.swing.JTextField();
        text_title = new javax.swing.JTextField();
        buton_browse = new javax.swing.JButton();
        buton_insert = new javax.swing.JButton();
        buton_delete = new javax.swing.JButton();
        buton_update = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        buton_find = new javax.swing.JButton();
        text_find = new javax.swing.JTextField();
        combobox_find = new javax.swing.JComboBox();
        label_find = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" HSQLDB Employee Database");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        buton_previous.setText("Previous");
        buton_previous.setEnabled(false);
        buton_previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_previousActionPerformed(evt);
            }
        });

        buton_next.setText("Next");
        buton_next.setEnabled(false);
        buton_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_nextActionPerformed(evt);
            }
        });

        jLabel1.setText("/");

        text_currentPage.setEditable(false);
        text_currentPage.setEnabled(false);
        text_currentPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_currentPageActionPerformed(evt);
            }
        });

        text_page.setEditable(false);
        text_page.setEnabled(false);
        text_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_pageActionPerformed(evt);
            }
        });

        label_email.setText("Email");

        label_firstname.setText("First Name");

        label_department.setText("Department");

        label_employee.setText("Employee ID");

        label_title.setText("Title");

        label_lastname.setText("Last Name");

        text_employee.setEnabled(false);
        text_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_employeeActionPerformed(evt);
            }
        });

        text_firstname.setEnabled(false);

        text_lastname.setEnabled(false);

        text_email.setEnabled(false);

        text_department.setEnabled(false);

        text_title.setEnabled(false);

        buton_browse.setText("Browse all entries");
        buton_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_browseActionPerformed(evt);
            }
        });

        buton_insert.setText("Insert new entry");
        buton_insert.setEnabled(false);
        buton_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_insertActionPerformed(evt);
            }
        });

        buton_delete.setText("Delete entry");
        buton_delete.setEnabled(false);
        buton_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buton_deleteMousePressed(evt);
            }
        });
        buton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_deleteActionPerformed(evt);
            }
        });

        buton_update.setText("Update entry");
        buton_update.setEnabled(false);
        buton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_updateActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 60));

        buton_find.setText("Find");
        buton_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_findActionPerformed(evt);
            }
        });

        text_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_findActionPerformed(evt);
            }
        });

        combobox_find.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Find by Last Name", "Find by Department", "Find by Title" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(combobox_find, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_find, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buton_find, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_find))
                .addContainerGap())
        );

        label_find.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        label_find.setText("Find by a property");
        label_find.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label_find.setDoubleBuffered(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buton_previous)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_currentPage)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_page, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(buton_next))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_title)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_employee)
                                    .addComponent(label_firstname)
                                    .addComponent(label_lastname)
                                    .addComponent(label_email)
                                    .addComponent(label_department))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_employee)
                                    .addComponent(text_firstname)
                                    .addComponent(text_lastname)
                                    .addComponent(text_email)
                                    .addComponent(text_department)
                                    .addComponent(text_title, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buton_browse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buton_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buton_insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buton_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_find)
                        .addContainerGap(304, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buton_previous)
                                .addComponent(text_currentPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buton_next)
                                .addComponent(text_page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_employee)
                            .addComponent(text_employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_firstname)
                            .addComponent(text_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_lastname)
                            .addComponent(text_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_email)
                            .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_department)
                            .addComponent(text_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_title)
                            .addComponent(text_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_find)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buton_insert)
                    .addComponent(buton_browse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buton_delete)
                    .addComponent(buton_update)))
        );

        buton_browse.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_currentPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_currentPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_currentPageActionPerformed

    private void buton_deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_deleteMousePressed
        // TODO add your handling code here:
                
        String sql = "DELETE FROM Employee WHERE ID="+text_employee.getText();
        
        try {
            dbh = new DBHandler(connectionString);
            dbh.executeQuery(sql);
            JOptionPane.showMessageDialog(this, "Silme işlemi yapıldı..");
            rowCount--;
            buton_previousActionPerformed(null);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lutfen bir ID giriniz");
        }
            
        
    }//GEN-LAST:event_buton_deleteMousePressed

    private void buton_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_previousActionPerformed
        // TODO add your handling code here:
               
        String sql = "SELECT * FROM EMPLOYEE WHERE LASTNAME like '%"+text_find.getText()+"%' and ID <"+text_employee.getText() +" order by id desc limit 1";
        
        try {
            dbh = new DBHandler(connectionString);
            ResultSet rs =dbh.executeQuery(sql);
            rs.first();
            int id=rs.getInt("ID");
            text_employee.setText(Integer.toString(id));
            text_employeeActionPerformed(evt);
            text_currentPage.setText(Integer.toString(Integer.parseInt(text_currentPage.getText())-1));
                   
                    
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Database başı!!");
        }
       
        
        
    }//GEN-LAST:event_buton_previousActionPerformed

    private void buton_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_nextActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM EMPLOYEE WHERE LASTNAME like '%"+text_find.getText()+"%' and ID >"+ text_employee.getText() +"limit 1";
        
        try {
            dbh = new DBHandler(connectionString);
            ResultSet rs =dbh.executeQuery(sql);
            rs.first();
            int id=rs.getInt("ID");
            text_employee.setText(Integer.toString(id));
            text_currentPage.setText(Integer.toString(Integer.parseInt(text_currentPage.getText())+1)); 
            text_employeeActionPerformed(evt);
                   
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database sonu!!");
        }
    }//GEN-LAST:event_buton_nextActionPerformed

    private void buton_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_insertActionPerformed
        // TODO add your handling code here:
        NewJFrame2 insert=new NewJFrame2();
        insert.text_id.setVisible(false);
        insert.label_firstname1.setVisible(false);
        insert.setVisible(true);
    }//GEN-LAST:event_buton_insertActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosed

    private void buton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_deleteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buton_deleteActionPerformed

    private void text_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_pageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_pageActionPerformed

    private void buton_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_browseActionPerformed
        // TODO add your handling code here:
        text_currentPage.setText("1");
        text_find.setText("");
        buton_next.setEnabled(true);
        buton_previous.setEnabled(true);
        buton_delete.setEnabled(true);
        buton_insert.setEnabled(true);
        buton_update.setEnabled(true);
        
        String sql = "SELECT * FROM EMPLOYEE";
                
                try {
                    dbh = new DBHandler(connectionString);
                    ResultSet rs =dbh.executeQuery(sql);
                    rs.first();
                    
                        int id=rs.getInt("ID");
                        text_employee.setText(Integer.toString(id));
                        text_employee.setText(Integer.toString(id));
                        //database den isim çekme
                        String firstname=rs.getString("FIRSTNAME");
                        text_firstname.setText(firstname);
                        //database den soyisim çekme
                        String lastname=rs.getString("LASTNAME");
                        text_lastname.setText(lastname);
                        //database den email çekme
                        String email=rs.getString("EMAİL");
                        text_email.setText(email);
                        //database den departman çekme
                        String department=rs.getString("DEPARTMENT");
                        text_department.setText(department);
                        //database den departman çekme
                        String title=rs.getString("TİTLE");
                        text_title.setText(title);
                        
                       rowCount = 1;
                    while (rs.next()) {//Print names in normal order
                         rowCount++;
                    }
                    text_page.setText(Integer.toString(rowCount));
                        
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lutfen database de bulunan bir lastname giriniz...");
                }
    }//GEN-LAST:event_buton_browseActionPerformed

    private void buton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_updateActionPerformed
        // TODO add your handling code here:
        NewJFrame2 update=new NewJFrame2();
        update.setVisible(true);
        update.text_firstname.setText(text_firstname.getText());
        update.text_lastname.setText(text_lastname.getText());
        update.text_email.setText(text_email.getText());
        update.text_department.setText(text_department.getText());
        update.text_title.setText(text_title.getText());
        update.text_id.setText(text_employee.getText());
        update.buton_ekle.setText("GUNCELLE");  
    }//GEN-LAST:event_buton_updateActionPerformed

    private void buton_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_findActionPerformed
        // TODO add your handling code here:
        text_currentPage.setText("1");
        buton_next.setEnabled(true);
        buton_previous.setEnabled(true);
        buton_delete.setEnabled(true);
        buton_insert.setEnabled(true);
        buton_update.setEnabled(true);
        
        switch(combobox_find.getSelectedIndex()){
            case 0:
            {   
                String sql = "SELECT * FROM EMPLOYEE WHERE LASTNAME like '%"+text_find.getText()+"%'";
                
                try {
                    dbh = new DBHandler(connectionString);
                   ResultSet rs =dbh.executeQuery(sql);
                    rs.first();
                    
                        int id=rs.getInt("ID");
                        text_employee.setText(Integer.toString(id));
                        //database den isim çekme
                        String firstname=rs.getString("FIRSTNAME");
                        text_firstname.setText(firstname);
                        //database den soyisim çekme
                        String lastname=rs.getString("LASTNAME");
                        text_lastname.setText(lastname);
                        //database den email çekme
                        String email=rs.getString("EMAİL");
                        text_email.setText(email);
                        //database den departman çekme
                        String department=rs.getString("DEPARTMENT");
                        text_department.setText(department);
                        //database den departman çekme
                        String title=rs.getString("TİTLE");
                        text_title.setText(title); 
                        rowCount = 1;
                    while (rs.next()) {//Print names in normal order
                         rowCount++;
                    }
                    text_page.setText(Integer.toString(rowCount));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lutfen database de bulunan bir lastname giriniz...");
                }
                
            
                break;
            }    
            case 1:
            {   
                String sql = "SELECT * FROM EMPLOYEE WHERE DEPARTMENT like '%"+text_find.getText()+"%'";
                
                try {
                    dbh = new DBHandler(connectionString);
                    ResultSet rs =dbh.executeQuery(sql);
                    rs.first();
                    
                        int id=rs.getInt("ID");
                        text_employee.setText(Integer.toString(id));
                        //database den isim çekme
                        String firstname=rs.getString("FIRSTNAME");
                        text_firstname.setText(firstname);
                        //database den soyisim çekme
                        String lastname=rs.getString("LASTNAME");
                        text_lastname.setText(lastname);
                        //database den email çekme
                        String email=rs.getString("EMAİL");
                        text_email.setText(email);
                        //database den departman çekme
                        String department=rs.getString("DEPARTMENT");
                        text_department.setText(department);
                        //database den departman çekme
                        String title=rs.getString("TİTLE");
                        text_title.setText(title); 
                        rowCount = 1;
                    while (rs.next()) {//Print names in normal order
                         rowCount++;
                    }
                    text_page.setText(Integer.toString(rowCount));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lutfen database de bulunan bir department giriniz...");
                }
                
            
                break;
            }    
            case 2:
            {   
                String sql = "SELECT * FROM EMPLOYEE WHERE TITLE like '%"+text_find.getText()+"%'";
                
                try {
                    dbh = new DBHandler(connectionString);
                    ResultSet rs =dbh.executeQuery(sql);
                    rs.first();
                    
                        int id=rs.getInt("ID");
                        text_employee.setText(Integer.toString(id));
                        //database den isim çekme
                        String firstname=rs.getString("FIRSTNAME");
                        text_firstname.setText(firstname);
                        //database den soyisim çekme
                        String lastname=rs.getString("LASTNAME");
                        text_lastname.setText(lastname);
                        //database den email çekme
                        String email=rs.getString("EMAİL");
                        text_email.setText(email);
                        //database den departman çekme
                        String department=rs.getString("DEPARTMENT");
                        text_department.setText(department);
                        //database den departman çekme
                        String title=rs.getString("TİTLE");
                        text_title.setText(title); 
                        rowCount = 1;
                    while (rs.next()) {//Print names in normal order
                         rowCount++;
                    }
                    text_page.setText(Integer.toString(rowCount));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lutfen database de bulunan bir title giriniz...");
                }
                
            
                break;
            }    
            default:
                break;
        }
    }//GEN-LAST:event_buton_findActionPerformed

    private void text_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_employeeActionPerformed
        // TODO add your handling code here:
        try {
            if(Integer.parseInt(text_employee.getText())>0){
                String sql = "SELECT * FROM Employee WHERE ID="+text_employee.getText();
                
                    try {
                        dbh = new DBHandler(connectionString);
                       ResultSet rs =dbh.executeQuery(sql);
                        rs.first();
                        //database den isim çekme
                        String firstname=rs.getString("FIRSTNAME");
                        text_firstname.setText(firstname);
                        //database den soyisim çekme
                        String lastname=rs.getString("LASTNAME");
                        text_lastname.setText(lastname);
                        //database den email çekme
                        String email=rs.getString("EMAİL");
                        text_email.setText(email);
                        //database den departman çekme
                        String department=rs.getString("DEPARTMENT");
                        text_department.setText(department);
                        //database den departman çekme
                        String title=rs.getString("TİTLE");
                        text_title.setText(title);    
                        text_page.setText(Integer.toString(rowCount));
                        
                 
                    }catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Lutfen bir ID giriniz");
                        text_firstname.setText("");
                        text_lastname.setText("");
                        text_email.setText("");
                        text_department.setText("");
                        text_title.setText("");
                        text_employee.setText("");
                    }
            }
        
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lutfen bir ID giriniz");
            text_firstname.setText("");
                        text_lastname.setText("");
                        text_email.setText("");
                        text_department.setText("");
                        text_title.setText("");
                        text_employee.setText("");
        }        
    }//GEN-LAST:event_text_employeeActionPerformed

    private void text_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_findActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_findActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                /* Create and display the form */
                
                        
            }   
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton_browse;
    private javax.swing.JButton buton_delete;
    private javax.swing.JButton buton_find;
    private javax.swing.JButton buton_insert;
    private javax.swing.JButton buton_next;
    private javax.swing.JButton buton_previous;
    private javax.swing.JButton buton_update;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox combobox_find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_department;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_employee;
    private javax.swing.JLabel label_find;
    private javax.swing.JLabel label_firstname;
    private javax.swing.JLabel label_lastname;
    private javax.swing.JLabel label_title;
    private static javax.swing.JTextField text_currentPage;
    private javax.swing.JTextField text_department;
    private javax.swing.JTextField text_email;
    public javax.swing.JTextField text_employee;
    private javax.swing.JTextField text_find;
    private javax.swing.JTextField text_firstname;
    private javax.swing.JTextField text_lastname;
    private static javax.swing.JTextField text_page;
    private javax.swing.JTextField text_title;
    // End of variables declaration//GEN-END:variables

    private void text_currentPageActionPerformed(MouseEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
